# Generated by Django 5.1.4 on 2024-12-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'city', 'street', 'house', 'apartment')},
        ),
    ]
